FROM node:16
WORKDIR /usr/src/app
COPY . ./

ARG LOOKERSDK_BASE_URL
ARG SERVER_PORT
ARG SERVICE_ACCOUNT_EMAIL

ENV LOOKERSDK_BASE_URL $LOOKERSDK_BASE_URL
ENV SERVER_PORT $SERVER_PORT
ENV SERVICE_ACCOUNT_EMAIL $SERVICE_ACCOUNT_EMAIL

RUN yarn install
RUN yarn gcp-build
EXPOSE 8080
CMD ["node", "./dist/index.js"]